### ISSUE TITLE
Unable to start a game with the Simple Client (Linux)

### ISSUE THREAD

**Issue by sunfl0w** [CAU-Kiel-Tech-Inf/gui#40]
Currently I am unable to start a game against the Simple Client in the GUI application. I don't know if this is related to the GUI or the Simple Client or the backend.

When I start the game the GUI locks up, even when the first player is a human. This is happening on my Linux machine, I have not tested this on Windows as of yet. Could this be a problem because of Java versions a I currently use OpenJDK 14 to start the GUI?

This is the log file created: 

<details><summary>Log</summary>
<p>

```java
11:15:39 WARN  sc.server.Configuration - Could not find server.properties at /run/media/sunfl0w/Common Storage/Projekte/SC/SC20_21/GUI/server.properties, will use default values!
11:15:39 INFO  sc.server.network.NewClientListener - Listening on port 13050 for incoming connections.
11:15:39 INFO  sc.server.network.ClientManager - ClientManager running.
11:15:41 DEBUG sc.gui.controller.AppController - Requested View change from START -> class sc.gui.view.GameCreationView
11:15:49 DEBUG sc.gui.controller.AppController - Requested View change from GAME_CREATION -> class sc.gui.view.GameView
11:15:49 DEBUG sc.gui.view.PiecesFragment - Color: RED
11:15:49 DEBUG sc.gui.model.BoardModel - Blocksize changed 16.0 -> 0.0
11:15:49 DEBUG sc.gui.controller.ClientController - creating and observing
11:15:49 INFO  sc.networking.clients.LobbyClient - Creating TCP Network for localhost:13050
11:15:49 INFO  sc.server.network.NewClientListener - A Client connected...
11:15:49 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
11:15:49 INFO  sc.server.network.ClientManager - Delegation done.
11:15:49 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@511ce690 to ReadyQueue.
11:15:49 INFO  sc.networking.clients.LobbyClient - Creating TCP Network for localhost:13050
11:15:49 INFO  sc.server.network.NewClientListener - A Client connected...
11:15:49 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
11:15:49 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@112bc17d to ReadyQueue.
11:15:49 INFO  sc.server.network.ClientManager - Delegation done.
11:15:49 INFO  sc.server.network.Client - Client authenticated as administrator
11:15:49 INFO  sc.server.gaming.GameRoomManager - Created new game of type swc_2021_blokus
11:15:49 DEBUG sc.gui.model.BoardModel - Blocksize changed 0.0 -> 27.5
11:15:49 DEBUG sc.gui.ControllingClient - lobby: game was prepared
11:15:49 DEBUG sc.gui.controller.ClientController - game listener: onUpdate
11:15:49 DEBUG sc.gui.controller.ClientController - ClientController got new update
11:15:49 DEBUG sc.gui.controller.ClientController - no gamestate, but sc.networking.clients.ControllingClient@50866637
11:15:49 DEBUG sc.gui.ComputerClient - will start /home/sunfl0w/Downloads/simpleclient-blokus-21.0.0.jar with arguments --host localhost --port 13050 --reservation 4f96adfc-8d27-4776-b299-71c2512c307b
11:15:49 DEBUG sc.gui.ControllingClient - lobby: 2955afca-8f63-40f9-95bf-ba278f31af35 game was observed
11:15:49 INFO  sc.server.gaming.GameRoom - Switching PAUSE from false to true.
11:15:49 INFO  sc.server.gaming.ReservationManager - Reservation 0590e014-dc38-400b-8ed7-b69f4f03e980 was redeemed.
11:15:49 INFO  sc.server.gaming.GameRoom - Game isn't ready yet.
11:15:49 DEBUG sc.gui.model.BoardModel - Blocksize changed 27.5 -> 24.65
11:15:50 INFO  sc.server.gaming.GameRoom - Switching PAUSE from true to false.
11:15:50 INFO  s.f.plugins.RoundBasedGameInstance - Sending MoveRequest to player null.
11:15:50 ERROR sc.networking.clients.XStreamClient - Unknown Communication Error
java.lang.NullPointerException: null
	at sc.framework.plugins.RoundBasedGameInstance.requestMove(RoundBasedGameInstance.java:206)
	at sc.framework.plugins.RoundBasedGameInstance.notifyActivePlayer(RoundBasedGameInstance.java:196)
	at sc.framework.plugins.RoundBasedGameInstance.afterPause(RoundBasedGameInstance.java:241)
	at sc.server.gaming.GameRoom.pause(GameRoom.java:594)
	at sc.server.Lobby.onRequest(Lobby.kt:94)
	at sc.server.network.Client.notifyOnPacket(Client.java:93)
	at sc.server.network.Client.onObject(Client.java:231)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:113)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)
	at java.base/java.lang.Thread.run(Thread.java:832)
11:15:50 WARN  sc.networking.clients.XStreamClient - Client sc.server.network.Client@112bc17d disconnected (Cause: UNKNOWN, Exception: {})
java.lang.NullPointerException: null
	at sc.framework.plugins.RoundBasedGameInstance.requestMove(RoundBasedGameInstance.java:206)
	at sc.framework.plugins.RoundBasedGameInstance.notifyActivePlayer(RoundBasedGameInstance.java:196)
	at sc.framework.plugins.RoundBasedGameInstance.afterPause(RoundBasedGameInstance.java:241)
	at sc.server.gaming.GameRoom.pause(GameRoom.java:594)
	at sc.server.Lobby.onRequest(Lobby.kt:94)
	at sc.server.network.Client.notifyOnPacket(Client.java:93)
	at sc.server.network.Client.onObject(Client.java:231)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:113)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)
	at java.base/java.lang.Thread.run(Thread.java:832)
11:15:50 INFO  sc.networking.clients.XStreamClient - Stopping XStreamClient ReceiveThread id:36 client:Client
11:15:50 WARN  sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
11:15:50 INFO  sc.server.network.ClientManager - Removing client sc.server.network.Client@112bc17d from client manager
11:15:50 INFO  sc.server.Lobby - sc.server.network.Client@112bc17d disconnected.
11:15:50 DEBUG sc.gui.ControllingClient - lobby: new state for 2955afca-8f63-40f9-95bf-ba278f31af35
11:15:50 DEBUG sc.gui.controller.ClientController - game listener: onUpdate
11:15:50 DEBUG sc.gui.controller.ClientController - ClientController got new update
11:15:50 DEBUG sc.gui.controller.ClientController - gamestate is GameState 1/0 -> BLUE (Start Piece: PENTO_W)
11:15:50 DEBUG sc.gui.controller.GameController - New game state
11:15:50 WARN  sc.networking.clients.XStreamClient - Client sc.networking.clients.LobbyClient@73013a0b disconnected (Cause: LOST_CONNECTION, Exception: {})
java.io.EOFException: null
	at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2198)
	at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:475)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:102)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)
	at java.base/java.lang.Thread.run(Thread.java:832)
11:15:50 INFO  sc.networking.clients.XStreamClient - Stopping XStreamClient ReceiveThread id:35 client:LobbyClient
11:15:50 WARN  sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
11:15:52 DEBUG sc.gui.controller.BoardController - Set-Move seems invalid from GUI at 1, 2
11:15:53 DEBUG sc.gui.controller.BoardController - Set-Move seems invalid from GUI at 0, 0
11:15:54 DEBUG sc.gui.controller.ClientController - game listener: onUpdate
11:15:54 DEBUG sc.gui.controller.ClientController - ClientController got new update
11:15:54 DEBUG sc.gui.controller.ClientController - gamestate is GameState 1/0 -> BLUE (Start Piece: PENTO_W)
11:15:54 DEBUG sc.gui.controller.GameController - New game state
11:15:55 INFO  sc.server.network.NewClientListener - Shutting down NewClientListener...
```

</p>
</details>

It seems like everything is normal until a move is requested by player null.

**Comment by anarchuser** [comment]
It seems the SimpleClient doesn't get loaded properly

**Comment by sunfl0w** [comment]
Same behavior can be seen when I try to use my own client that is started with a shell script. So this looks like a problem with clients in general
